import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import axios from 'axios';
import './MeetingDetail.css';
import API_BASE_URL from '../config';
import TaskExecutionSection from '../components/TaskExecutionSection';

const MeetingDetail = () => {
  const { id } = useParams();
  const [meeting, setMeeting] = useState(null);

  const fetchMeeting = async () => {
    try {
      const res = await axios.get(`${API_BASE_URL}/api/meetings/${id}`);
      setMeeting(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchMeeting();
  }, [id]);

  if (!meeting) return <div className="module-container">LOADING_SESSION_DATA...</div>;

  return (
    <div className="module-container meeting-detail">
      <header className="detail-header">
        <Link to="/meetings" className="btn-back">← BACK_TO_LIST</Link>
        <div className="header-info">
          <h1>{meeting.title}</h1>
          <span className={`badge ${meeting.sentiment?.toLowerCase() === 'positive' ? 'info' : 'warning'}`}>
            MOOD: {meeting.sentiment || 'ANALYZING'}
          </span>
        </div>
      </header>

      <div className="detail-grid">
        <section className="cyber-panel summary-section">
          <h2>AI_SUMMARY</h2>
          <p style={{ whiteSpace: 'pre-wrap' }}>{meeting.summary || 'Summary is being generated by AI...'}</p>
        </section>

        <section className="cyber-panel tasks-section">
          <h2>ACTION_ITEMS</h2>
          <div className="task-list">
            {meeting.actionItems?.map((item, idx) => (
              <div key={idx} className="task-item">
                <div className="task-top">
                  <span className="assignee">{item.assignee}</span>
                  <span className={`task-status ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span>
                </div>
                <p>{item.task}</p>
              </div>
            ))}
          </div>
        </section>

        <TaskExecutionSection meeting={meeting} fetchMeeting={fetchMeeting} />

        <section className="cyber-panel transcript-section">
          <h2>TRANSCRIPT</h2>
          <div className="transcript-content" style={{ whiteSpace: 'pre-wrap' }}>
            {meeting.transcript || 'Full transcript will appear here once processed.'}
          </div>
        </section>
      </div>
    </div>
  );
};

export default MeetingDetail;
