import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import axios from 'axios';
import './MeetingDetail.css';
import API_BASE_URL from '../config';
import TaskExecutionSection from '../components/TaskExecutionSection';

const MeetingDetail = () => {
  const { id } = useParams();
  const [meeting, setMeeting] = useState(null);

  const fetchMeeting = async () => {
    try {
      const res = await axios.get(`${API_BASE_URL}/api/meetings/${id}`);
      setMeeting(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchMeeting();
  }, [id]);

  if (!meeting) return <div className="module-container">LOADING_SESSION_DATA...</div>;

  return (
    <div className="module-container meeting-detail">
      <header className="detail-header">
        <Link to="/meetings" className="btn-back">← BACK_TO_LIST</Link>
        <div className="header-info">
          <h1>{meeting.title}</h1>
          <span className={`badge ${meeting.sentiment?.toLowerCase() === 'positive' ? 'info' : 'warning'}`}>
            MOOD: {meeting.sentiment || 'ANALYZING'}
          </span>
        </div>
      </header>

      <div className="detail-grid">
        {/* Agent Execution & Security Observability Panel */}
        <section className="cyber-panel agent-observability-section" style={{ gridColumn: '1 / -1' }}>
          <div className="agent-header">
            <h2>🤖 AGENT WORKFLOW & OBSERVABILITY TRACE</h2>
            <div className="security-badges">
              <span className={`badge ${meeting.securityStatus?.toLowerCase().includes('threat') || meeting.securityStatus?.toLowerCase().includes('suspicious') ? 'warning' : 'info'}`}>
                SECURITY STATUS: {meeting.securityStatus || 'No Threat Detected'}
              </span>
              {meeting.incidentTicket && (
                <Link to={`/soc/resolution/${meeting.incidentTicket.ticketId}`} className="badge critical" style={{ textDecoration: 'none' }}>
                  🚨 INCIDENT TICKET #{meeting.incidentTicket.ticketId} VIEW
                </Link>
              )}
            </div>
          </div>

          {/* Timeline of Agent Actions */}
          <div className="agent-timeline">
            {(!meeting.agentActions || meeting.agentActions.length === 0) ? (
              <p className="dim-text">Agent action log is being initialized...</p>
            ) : (
              meeting.agentActions.map((act, idx) => {
                const isPlan = act.type === 'AGENT_PLAN';
                const isStart = act.type === 'TOOL_START';
                const isComplete = act.type === 'TOOL_COMPLETE';
                const isError = act.type === 'TOOL_ERROR' || act.type === 'WORKFLOW_ERROR';
                const isFinish = act.type === 'WORKFLOW_FINISH';

                return (
                  <div key={idx} className={`timeline-item ${isComplete ? 'complete' : isError ? 'error' : isPlan ? 'plan' : isFinish ? 'finish' : ''}`}>
                    <div className="timeline-node">
                      {isPlan ? '🧠' : isStart ? '⚙️' : isComplete ? '✅' : isError ? '❌' : '🏁'}
                    </div>
                    <div className="timeline-content">
                      <div className="timeline-title-row">
                        <span className="action-type">[{act.type}]</span>
                        <span className="action-time">{new Date(act.timestamp).toLocaleTimeString()}</span>
                      </div>
                      <p className="action-msg">{act.message}</p>
                      {act.metadata && Object.keys(act.metadata).length > 0 && (
                        <div className="action-meta">
                          {Object.entries(act.metadata).map(([k, v]) => (
                            <span key={k} className="meta-chip">{k}: {typeof v === 'object' ? JSON.stringify(v) : String(v)}</span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </section>

        <section className="cyber-panel summary-section">
          <h2>AI_SUMMARY</h2>
          <p style={{ whiteSpace: 'pre-wrap' }}>{meeting.summary || 'Summary is being generated by AI...'}</p>
        </section>

        <section className="cyber-panel tasks-section">
          <h2>ACTION_ITEMS</h2>
          <div className="task-list">
            {meeting.actionItems?.map((item, idx) => (
              <div key={idx} className="task-item">
                <div className="task-top">
                  <span className="assignee">{item.assignee}</span>
                  <span className={`task-status ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span>
                </div>
                <p>{item.task}</p>
              </div>
            ))}
          </div>
        </section>

        <TaskExecutionSection meeting={meeting} fetchMeeting={fetchMeeting} />

        <section className="cyber-panel transcript-section">
          <h2>TRANSCRIPT</h2>
          <div className="transcript-content" style={{ whiteSpace: 'pre-wrap' }}>
            {meeting.transcript || 'Full transcript will appear here once processed.'}
          </div>
        </section>
      </div>
    </div>
  );
};

export default MeetingDetail;
